### PR TITLE
Update DCF77_RTC_LCD.ino

### PR DESCRIPTION
**Pull request by trombose009**
I tried to make some changes here. I don't know if it works

### CODE REVIEW

**Comment by maciejbaur** [comment]
Thx for that idea. Already upload to the clock and testing. Initial sync was done. I'll check at midnight what happens.

**Comment by maciejbaur** [comment]
I did some modifications and looks promising. I need to test it in next day or two to verify if night syncing is done.

**Comment by maciejbaur** [comment]
It seams that RTC will be reset at night but the problem is that there is no indication if DCF77 is receiving or not. When DCF signal is recoded correctly frst time dcf.synced() is always true even if DCF receiver is disconnected. So I have no track of incomming signal. In that case RTC will be resynced in the night even if actual DCF is not received. So this is not OK but I suppose this is Funkuhr library issue.

**Comment by trombose009** [comment]
I am sure this could be solved. I have no issues with the clock in the vid. It is running 24/7 without problems using the code you can download and is syncing every full hour.

Gesendet von Yahoo Mail auf Android 
 
  Am So., Jan. 10, 2021 at 13:06 schrieb maciejbaur<notifications@github.com>:   


It seams that RTC will be reset at night but the problem is that there is no indication if DCF77 is receiving or not. When DCF signal is recoded correctly frst time dcf.synced() is always true even if DCF receiver is disconnected. So I have no track of incomming signal. In that case RTC will be resynced in the night even if actual DCF is not received. So this is not OK but I suppose this is Funkuhr library issue.

**Comment by maciejbaur** [comment]
OK, I will check your code.
What is happening when DCF signal is not available but hourly sync is called?

**Comment by trombose009** [comment]
As far as I remember, the signal is checked in the If Statement.

**Comment by maciejbaur** [comment]
OK. I've downloaded your code but what dcf77 library do you use? Maybe it could help? I use Funkuhr.h but I can see dcf77.h in your code. Maybe it offers more than mine?

**Pull request merged**
